blueprint:
  name: Turn off Lights and/or Switches after Time has elapsed
  source_url: https://gist.githubusercontent.com/SteveJHammond/b578f64dd269ced87718f46d5801ac96/raw/d7deb5802fae68ca362c252aead6d5f883041b94/Turn%2520Off%2520Light%2520or%2520Switch%2520After%2520Time.yaml
  description: Given a set of lights and/or switches entities, watch for it turning on, and then turn it off
    after a certain period of time.
  domain: automation
  input:
    lights_switches:
      name: Lights and Switches
      description: Select the lights and/or switches to monitor and control
      selector:
        entity:
          domain:
          - light
          - switch
          multiple: true
    duration:
      name: Duration
      description: The duration to leave the lights and/or switches on for
      selector:
        duration: {}
trigger:
- platform: state
  entity_id: !input lights_switches
  to: 'on'
  for: !input duration
condition: []
action:
- service: homeassistant.turn_off
  data: {}
  entity_id: !input lights_switches
mode: single
